### PR TITLE
systemd: start device units directly

### PR DESCRIPTION
**Pull request by crawford**
A few systemd.conf attendees pointed out that device units could be
started directly. We'll use that approach instead of the transient
units.

### CODE REVIEW

**Comment by crawford** [comment]
@vcaputo do you remember why we used the transient units in the first place?

**Comment by vcaputo** [comment]
Our transient unit isn't starting device units, it's starting a throwaway service which _depends_ on the requisite device units as a means of synchronizing with their appearance - an asynchronous automatic thing done in response to udev events.

I don't understand how starting them directly is analagous, what if they don't exist yet when you go to start them directly?

**Comment by crawford** [comment]
Starting a device unit is a safe thing to do here. Since systemd can't control the state of this type of unit, it will wait for the state to align with it's expectation. So in this case, it will wait for that device to show up.

**Comment by vcaputo** [comment]
news to me, provided it works, lgtm

**Pull request merged**
