### PR TITLE
internal: Honour HTTP proxy environment vars

### PR DESCRIPTION
**Pull request by donaldh**
This provides the same behaviour as the default http.Transport

### CODE REVIEW

**Comment by lucab** [comment]
Thanks for the PR! Just for reference: are you passing the proxy env on the kernel command-line at boot or some other way?

**Comment by donaldh** [comment]
Ignition is used internally by
https://github.com/kubernetes/kubernetes-anywhere

The README.md hints at what it is doing.

Cheers!

**Comment by dgonyeo** [comment]
This change doesn't really impact Container Linux's usage of Ignition in any way since users can't inject environment variables into Ignition's environment in CL, so I don't have any concerns with this. Based on an oob chat, if we end up adding proxy settings to Ignition configs at any point in the future that would take precedence over the environment.

Approving this, and leaving it open for the day in case anyone else wants to provide their opinion.

**Comment by bgilbert** [comment]
@donaldh It'd be a good idea to add a unit test for this, since it seems like the kind of functionality that could be accidentally broken during a refactor.

**Comment by dgonyeo** [comment]
I also just merged a PR that conflicts with this. If you rebase on master and move your change to [further down in the same file](https://github.com/coreos/ignition/blob/644a87dd0210c35ea93c698f2c96dc678b737ecf/internal/resource/http.go#L178) that would be great.

**Comment by donaldh** [comment]
Superseded by https://github.com/coreos/ignition/pull/507

**Pull request closed without merging**
