### PR TITLE
Add blackbox testing

### PR DESCRIPTION
**Pull request by arithx**
Adds tests/blackbox_test.go which will build a multi-partitioned
virtual disk according to the spec present in data/disk.yaml,
run ignition based on data/config.ign, and then validate the
result against data/diskOut.yaml

### CODE REVIEW

**Comment by dgonyeo** [comment]
Why not store the tests as harcoded golang structs? That's what they end up as internally anyway, and it'd save you from having to pull in a yaml library.

**Comment by arithx** [comment]
ok to test

**Comment by arithx** [comment]
retest this please

**Comment by arithx** [comment]
retest this please

**Pull request closed without merging**
