### PR TITLE
config: be more specific on JSON unmarshal failure

### PR DESCRIPTION
**Pull request by jonboulle**
Use a library from camlistore to help pinpoint exactly where the problem
is if invalid JSON is supplied to Ignition.

### CODE REVIEW

**Comment by vcaputo** [comment]
@jonboulle looks like you omitted the actual contents of "third_party/github.com/camlistore/camlistore/pkg/errorutil"

**Comment by jonboulle** [comment]
How on earth did the 1.5 succeed on Travis?!

**Comment by jonboulle** [comment]
Updated..

**Comment by vcaputo** [comment]
lgtm, thank you sir

**Pull request merged**
