### PR TITLE
Move Ignition-Dracut into Ignition

### PR DESCRIPTION
**Pull request by darkmuggle**
dracut: remove CoreOS specific bits from Dracut
    
CoreOS specific modules have been will be moved over https://github.com/coreos/fedora-coreos-config.

The approach came from https://github.com/coreos/fedora-coreos-tracker/issues/511

### CODE REVIEW

**Comment by cgwalters** [comment]
Overall big +1 on the idea!

**Comment by darkmuggle** [comment]
The CI failure on this is expected since `rootfs.uuid` relies not the changes in https://github.com/coreos/fedora-coreos-config/pull/526

Local test:
```
$ fcosa kola run rootfs.uuid
⚠️  Skipping kola test pattern "fcos.internet":
⚠️  https://github.com/coreos/coreos-assembler/pull/1478
⚠️  Skipping kola test pattern "podman.workflow":
⚠️  https://github.com/coreos/coreos-assembler/pull/1478
kola -p qemu-unpriv --output-dir tmp/kola run rootfs.uuid --denylist-test fcos.internet --denylist-test podman.workflow
=== RUN   rootfs.uuid
=== RUN   rootfs.uuid/RandomUUID
--- PASS: rootfs.uuid (37.20s)
    --- PASS: rootfs.uuid/RandomUUID (0.36s)
PASS, output in tmp/kola
```

**Comment by jlebon** [comment]
This roughly looks good to me! Some things that popped out:
- the conditional networking stuff, which Benjamin opened PRs for already in https://github.com/coreos/fedora-coreos-config/pull/527 and https://github.com/coreos/ignition-dracut/pull/200
- I think `99emergency` probably belongs better in f-c-c too? ISTM like the behaviour of what to do on initrd failure is more of a distro-specific thing than something we want to dictate with Ignition.

**Comment by darkmuggle** [comment]
> * the conditional networking stuff, which Benjamin opened PRs for already in [coreos/fedora-coreos-config#527](https://github.com/coreos/fedora-coreos-config/pull/527) and [coreos/ignition-dracut#200](https://github.com/coreos/ignition-dracut/pull/200)

I *think* that we can coordinate this with @bgilbert's proposed changes easily. 

> * I think `99emergency` probably belongs better in f-c-c too? ISTM like the behaviour of what to do on initrd failure is more of a distro-specific thing than something we want to dictate with Ignition.

Ah, good catch. I did that in my first experiment but after an unreconcilable rebase I re-did it and missed it. Repushed.

**Comment by darkmuggle** [comment]
With https://github.com/coreos/fedora-coreos-config/pull/526 the packaging repo [1] and build [2] this passes Kola.
[1] https://src.fedoraproject.org/fork/darkmuggle/rpms/ignition/c/f9230b7d8393c6b4dba45dfa678c2aac5ddf8b51?branch=v2.5.0-prep
[2] https://copr.fedorainfracloud.org/coprs/darkmuggle/ignition/build/1574639

All tests passed. Ready for review.

**Comment by darkmuggle** [comment]
This build passes local testing:
[1] https://copr.fedorainfracloud.org/coprs/build/1574662
[2] https://src.fedoraproject.org/fork/darkmuggle/rpms/ignition/c/9cd46f69ba5e1e794e41edc8139bb2eee1fed116?branch=v2.5.0-prep
[3] https://github.com/coreos/fedora-coreos-config/pull/526

**Pull request merged**
