### PR TITLE
docs: Adds a linebreak in examples.md to assist markup parser.

### PR DESCRIPTION
**Pull request by ndouglas**
I think this will fix a formatting issue on coreos.com.

Sorry, flubbed the commit a little by not prefixing with "docs:" or specifying where the edit occurred.

### CODE REVIEW

**Comment by euank** [comment]
You should be able to `git commit --amend` and `git push -f` to update the commit title.

The change LGTM apart from the commit title nit.

**Comment by ndouglas** [comment]
Let's try that.

**Comment by crawford** [comment]
Can you rebase your changes onto master? (`git fetch origin && git rebase origin/master && git push origin ndouglas-patch-1 -f`)

**Comment by euank** [comment]
Oh, whoops, this is my bad! I ran into the malformed bit on the website and PR'd it myself over in #321 after totally forgetting about this one... I should have come back and merged this instead, sorry 🙇

**Pull request closed without merging**
