### PR TITLE
build: add ARM64 to test matrix

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
This will help prevent stupid bugs like https://github.com/coreos/bugs/issues/1175.

**Comment by crawford** [comment]
This is proving to be quite challenging. I'm giving up for now.

**Comment by glevand** [comment]
@lupan2005 Please take a look at this and see if you can get something to work.

**Comment by mischief** [comment]
I believe crawford discovered that Travis needs to update their gimme script to resolve this.

**Comment by glevand** [comment]
I've been working on this, but it seems we are blocked by https://github.com/travis-ci/apt-package-whitelist/issues/2812, which is needed for arm64 cgo support.

**Comment by glevand** [comment]
@crawford https://github.com/coreos/ignition/pull/235 continues this, so we can close this PR.

**Pull request closed without merging**
