### PR TITLE
ci: migrate to new coreos-ci project

### PR DESCRIPTION
**Pull request by jlebon**
We can use the new `cosaPod` and `fcosBuild` custom steps.

### CODE REVIEW

**Comment by jlebon** [comment]
Requires: https://github.com/coreos/coreos-ci/pull/7

**Comment by miabbott** [comment]
I merged the dependent PR, so...

/approve

**Comment by cgwalters** [comment]
Cool stuff!

**Comment by cgwalters** [comment]
Just a note here, this isn't trying to run any of Ignition's "blackbox" tests yet; would be neat to try to stub out adapting those too.

**Comment by jlebon** [comment]
Yeah, we need to have a look through that CL Jenkins instance and see what else should be siphoned out.

**Pull request merged**
