### PR TITLE
Update hostname example

### PR DESCRIPTION
**Pull request by karmab**

### CODE REVIEW

**Comment by lucab** [comment]
@karmab thanks for the PR. This seems to assume that Ignition is provisioning a node that already has an `/etc/hostname` populated (i.e. a pre-assigned hostname), which seems suspicious. Which distribution and version is this happening on?

**Comment by karmab** [comment]
@lucab happened on fedora coreos 30

**Comment by jlebon** [comment]
More context in https://github.com/coreos/coreos-assembler/pull/497#issuecomment-492326051.

**Comment by jlebon** [comment]
With https://github.com/coreos/coreos-assembler/pull/522 I think we should be OK now.

**Comment by arithx** [comment]
Might still be worth it to merge the docs change though as other distros might have `/etc/hostname` present on first boot.

**Pull request merged**
