### PR TITLE
glide: update go-systemd to v18 

### PR DESCRIPTION
**Pull request by lucab**
This updates go-systemd to latest release, and massages glade manifests to avoid floating versions on transitive dependencies.

### CODE REVIEW

**Comment by lucab** [comment]
@arithx we only use go-systemd subpackages `dbus` and `unit` here, which shouldn't depend on `coreos/pkg`. But I may have missed something, where did you see that dependency here?

**Comment by ajeddeloh** [comment]
Are the transitive deps causing problems? Pinning them makes it hard to update later (although marking them as transitive will help)

**Comment by arithx** [comment]
@lucab ah forgot about the glide stripping for non-used components, was just checking the `go-systemd` dependencies.

**Comment by lucab** [comment]
@ajeddeloh they are not right giving problems now (I've only seen the unrelated floating now and pinned it). They can float to incompatible version though. I think we already have go-dbus here for that reason, as it breaks APIs on master from time to time.

**Comment by ajeddeloh** [comment]
Hrmm. I think I prefer to let things float unless they _need_ to be pinned. My general thought was we should update all transient deps whenever we update a dep in general (direct deps should be pinned). If something breaks we should pin the thing with a comment on why it's pinned.

I could definitely be convinced otherwise though.

**Comment by lucab** [comment]
This is a fuzzy Go topic and there is no good absolute answer.

The current status is the result of previous painful bumps like https://github.com/coreos/ignition/commit/f44956e881d86d35f3c173bde27abee3fb572ddc.

Expunging transitive deps from here would be the correct way, but Go does not have a common way of communicating requirements, so some transitive dependencies may end up being wrongly unconstrained. That means that somebody trying to update a specific library may have to deal with tracking down breakage in completely unrelated transitive deps of another library (see above).

This pins some more transitive depedencies with comments. That means on the next bump one has to go and update the transitive dependencies too, but blast radius from bumps should be self-contained.

This becomes non-tractable once we have shared transitive dependencies at different versions. In that case we just give up and blame Go.

**Pull request merged**
