### PR TITLE
Update AWS for IMDSv2

### PR DESCRIPTION
**Pull request by dustin-decker**
Updates AWS dep to provide support for IMDSv2

https://blog.appsecco.com/getting-started-with-version-2-of-aws-ec2-instance-metadata-service-imdsv2-2ad03a1f3650

Signed-off-by: Dustin Decker <dustin.decker@protonmail.com>

### CODE REVIEW

**Comment by bgilbert** [comment]
Confirmed that regenerating `vendor/` matches the commit here.

**Comment by bgilbert** [comment]
ok to test

**Comment by sohankunkerkar** [comment]
ok to test

**Comment by arithx** [comment]
retest this please

**Comment by sohankunkerkar** [comment]
@bgilbert  I was wondering if we need to get this [https://github.com/coreos/ignition/issues/989] change in before testing this PR?
I was trying to launch an AWS instance with this PR changes, but it appears that the FCOS VM doesn't boot up properly and it goes into an emergency exit mode.

**Comment by lucab** [comment]
> can we still fetch via IMDSv1 if IMDSv2 is disabled in the instance?

Is this "v1 enabled, v2 disabled" mode actually possible? It doesn't seem from my reading of the docs (which seem to allow only "v1 AND v2 enabled", "none enabled", "v1 only enabled"), but it may not reflect the reality.

**Comment by sohankunkerkar** [comment]
> > can we still fetch via IMDSv1 if IMDSv2 is disabled in the instance?
> 
> Is this "v1 enabled, v2 disabled" mode actually possible? It doesn't seem from my reading of the docs (which seem to allow only "v1 AND v2 enabled", "none enabled", "v1 only enabled"), but it may not reflect the reality.

@lucab Yes, you're right. It's not possible to disable v2 and still use the `v1` metadata. I was just trying to verify if that's a possibility. I marked that checkbox to indicate that that test case was being covered. Sorry for the confusion there.

**Comment by dustin-decker** [comment]
Afterburn support is being worked on in https://github.com/coreos/afterburn/pull/426

**Pull request merged**
