### PR TITLE
tests/partitioning: add minversion to complex mb

### PR DESCRIPTION
**Pull request by ajeddeloh**
Do not hardcode 2.3.0 in the config. Set minversion to 2.3.0 like the
other tests do.

### CODE REVIEW

**Comment by ajeddeloh** [comment]
Fixes https://github.com/coreos/ignition/issues/685

**Comment by arithx** [comment]
Looks like we have the exact same issue in the Preemption tests.

As well for #685 the following tests are also affected:

* `TestIgnitionBlackBox/Empty_Userdata`
* `TestIgnitionBlackBoxNegative/Version_Only_Config_2.5.0-experimental`
* `TestIgnitionBlackBoxNegative/Version_Only_Config_2.3.0-experimental`
* `TestIgnitionBlackBoxNegative/Version_Only_Config_2.4.0` (not sure this still exists, was going through a previous run log)
* `TestIgnitionBlackBoxNegative/Invalid_Version`

**Comment by ajeddeloh** [comment]
Preemption tests are weird. They have multiple configs and the test runner only knows about one of them. We could add it to that test but it would only affect the one config.
The other tests intentionally do not use the minversion logic.

**Comment by arithx** [comment]
For preemption tests couldn't we just put `$version` in here: https://github.com/coreos/ignition/blob/master/tests/positive/general/preemption.go#L54
as well as the `ConfigMinVersion`? They're all generated inside of that function.

For the others we should probably add some sort of special casing in the `Register` function to handle that case properly.

**Comment by ajeddeloh** [comment]
For the preemption test, no. The only config that gets changed is the one in the struct. If we added $version there we'd error out since the other configs wouldn't get updated.

What's the problem with the current register behavior for them? The trailing _?

**Pull request merged**
