### PR TITLE
Backport configuring a proxy that ignition can honor during replace and append fetches

### PR DESCRIPTION
**Pull request by dragan**
This is a backport of the #733 changes to the `spec2x` branch.

### CODE REVIEW

**Comment by dragan** [comment]
No problem, thanks for the bump.

Also, I noticed that the `blackboxtests` aren't running for this PR yet.

**Comment by arithx** [comment]
ok to test

**Comment by ajeddeloh** [comment]
Ran this through a kola qemu run with CL as a final check. Passed. Merging.

**Comment by dragan** [comment]
Thanks ignition team! 🙌

**Comment by ajeddeloh** [comment]
This will be included in the next Container Linux alpha, which should be out next week.

**Pull request merged**
