### PR TITLE
config/*/append: add append function back

### PR DESCRIPTION
**Pull request by ajeddeloh**
cc @dghubble

### CODE REVIEW

**Comment by arithx** [comment]
Should we just revert https://github.com/coreos/ignition/commit/6b019bb214781a6abc5ce377bf62cd3a804e4516 instead?

**Comment by ajeddeloh** [comment]
Nope, since that one doesn't have 2.3.0 stable or 2.4.0-experimental.

**Comment by arithx** [comment]
Ah fair point, I should have checked that first, I didn't remember how old that code was and just dug up the original merge commit.

**Comment by ajeddeloh** [comment]
I updated the commit message to include that commit hash at least.

**Comment by ajeddeloh** [comment]
Added tests back. the 2.4.0-exp is the same as the 2.3.0 test, which I think should be sufficient, especially since the code is the same for all versions.

**Comment by dghubble** [comment]
Thanks! :tada:

**Pull request merged**
