### PR TITLE
ignition.md: fix table formatting

### PR DESCRIPTION
**Pull request by SpencerBrown**
on GitHub Web Browser view, it's corrupted

### CODE REVIEW

**Comment by crawford** [comment]
That's a bummer. All docs should be limited to 80 columns, so we need to break the descriptions between lines. Is there a GitHub syntax that will make this work? Otherwise, we'll just have to use a list.

**Comment by SpencerBrown** [comment]
Not that I'm any kind of expert, but I don't know of any way to do what you want to do in [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/)

Any chance of giving up on the 80 column limitation?

**Comment by crawford** [comment]
> Any chance of giving up on the 80 column limitation?

No. Our docs need to be readable as plain text as well as rendered documents.

The table can be restructured as a list:

```
 - cmdline: fetches the config from the URL provided via the "coreos.config.url"
            kernel boot option.
 - file: read the config from a file named "config.json" in the current working
         directory.
```

**Comment by crawford** [comment]
LGTM after you squash and prefix the commit with "docs: ".

**Comment by vcaputo** [comment]
@SpencerBrown ping

**Pull request closed without merging**
