### PR TITLE
providers: add initial packet support

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
This has not been tested yet.

**Comment by vcaputo** [comment]
looks fine so far

**Comment by crawford** [comment]
GitHub/Travis fucked up, so I bumped that last commit just to retrigger the test.

**Comment by bison** [comment]
I rebased this on top of master and did some basic testing of the files stage on Packet. Seems to work.

Anything I can do to help test further?

**Comment by crawford** [comment]
I need to validate that the networking comes up properly in the initramfs, but I'm out on vacation this week. I should have it done for the next Alpha.

**Comment by crawford** [comment]
@betawaffle and I verified that this works.

**Pull request merged**
