### PR TITLE
Bump go-semver dependency to add YAML unmarshaling

### PR DESCRIPTION
**Pull request by dghubble**

### CODE REVIEW

**Comment by crawford** [comment]
config/vendor.manifest needs to be updated.

**Comment by dghubble** [comment]
Updated. Is that associated with some tool or format, or just maintained by hand?

**Comment by crawford** [comment]
LGTM. It's just done by hand until we find a reasonable tool.

**Comment by dghubble** [comment]
Erm, I don't seem to have merge privileges on this.

**Pull request merged**
